FROM node:alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

COPY src/package.json ./src
COPY src/package-lock.json ./src

RUN npm run c-install

COPY . ./

CMD ["npm", "run", "start"]

